name: InspectMaster

on:
  push:
    branches: [ master ]

jobs:
  self-test:
   runs-on: ubuntu-latest
   name: Self Test
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Inspect
       uses: nbadal/inspectcode-action
       with:
          solution: './APIGateway.Core.sln'